project:
  type: website

website:
  title: "Jeffrey Pullin"
  navbar:
    right:
      - about.qmd
      - icon: github
        href:  https://github.com/jeffreypullin
      - icon: twitter
        href: https://twitter.com/jeffreypullin
format:
  html:
    theme: cosmo
    css: styles.css



